---
- name: assert required variables are set and have reasonable values
  assert:
    that:
      - (borg_olafnorge_de_labels | length) > 0
      - (borg_olafnorge_de_network_definitions | length) > 0
      - (borg_olafnorge_de_networks | length) > 0
      - borg_olafnorge_de_environment is defined
      - borg_olafnorge_de_environment.app_key is defined
      - (borg_olafnorge_de_environment.app_key | length) > 0
      - borg_olafnorge_de_environment.db_password is defined
      - (borg_olafnorge_de_environment.db_password | length) > 0
      - borg_olafnorge_de_environment.rollbar_enabled is defined
      - (not (borg_olafnorge_de_environment.rollbar_enabled)) or
        (
        (borg_olafnorge_de_environment.rollbar_enabled) and
        (borg_olafnorge_de_environment.rollbar_token is defined) and
        ((borg_olafnorge_de_environment.rollbar_token | length) > 0)
        )

- name: create secrets for borg.example.com
  docker_secret:
    data: "{{ item.value.data }}"
    name: "{{ item.value.name }}"
    state: present
  no_log: yes
  with_dict: "{{ borg_olafnorge_de_secrets }}"
  when: borg_olafnorge_de_use_secrets

- name: write crontab skeleton
  template:
    dest: "{{ borg_olafnorge_de_crontab_path }}"
    mode: 0600
    src: crontab.j2
  register: borg_olafnorge_de_crontab_templated

- name: register dynamic name of crontab skeleton
  set_fact:
    borg_olafnorge_de_configs_dict: "{'borg-crontab-{{ borg_olafnorge_de_crontab_templated.checksum[:10] }}':{'file':'{{ borg_olafnorge_de_crontab_path }}'}}"

- name: spawn borg.example.com service
  docker_stack:
    compose:
      - "{{ borg_olafnorge_de_compose }}"
    name: "{{ borg_olafnorge_de_name }}"
    prune: yes
    state: present
